function Section({ title, children }) {
  return (
    <section className="mb-8">
      <h2 className="mb-2 text-xl font-semibold text-text-primary">{title}</h2>
      <div className="space-y-3 leading-relaxed">{children}</div>
    </section>
  );
}

export default function TermsOfService() {
  return (
    <div className="mx-auto max-w-3xl px-6 py-16 text-text-secondary">
      <h1 className="mb-2 text-3xl font-bold text-text-primary">Terms of Service</h1>
      <p className="mb-8 text-sm text-text-muted">Last updated: July 2026</p>

      <Section title="1. Acceptance of Terms">
        <p>
          By creating an account or using UPSC Mentor, you agree to these
          Terms of Service. If you do not agree, please do not use the
          platform.
        </p>
      </Section>

      <Section title="2. Account Responsibilities">
        <p>
          You are responsible for maintaining the confidentiality of your
          account credentials and for all activity under your account.
        </p>
      </Section>

      <Section title="3. AI-Generated Content">
        <p>
          Mains evaluations, test diagnostics, notes feedback, and mentor
          chat responses are generated by AI models and are intended as study
          aids, not as guarantees of official UPSC scoring or exam outcomes.
          Always cross-check important facts against official sources.
        </p>
      </Section>

      <Section title="4. Fair Use & Rate Limits">
        <p>
          AI-backed features (answer evaluation, test analysis, mentor chat)
          are rate-limited per day to keep the service usable and sustainable
          for everyone. Attempting to circumvent these limits may result in
          account restrictions.
        </p>
      </Section>

      <Section title="5. Intellectual Property">
        <p>
          The platform's design, code, and original content are the property
          of UPSC Mentor. Curated third-party resources (NCERT texts, PYQs,
          government reports) remain the property of their respective
          publishers and are linked or referenced, not claimed as our own.
        </p>
      </Section>

      <Section title="6. Termination">
        <p>
          We reserve the right to suspend or terminate accounts that violate
          these terms, abuse the platform, or attempt to disrupt its normal
          operation.
        </p>
      </Section>

      <Section title="7. Limitation of Liability">
        <p>
          UPSC Mentor is provided "as is." We are not liable for exam outcomes,
          data loss, or service interruptions, to the maximum extent permitted
          by law.
        </p>
      </Section>

      <Section title="8. Governing Law">
        <p>These terms are governed by the laws of India.</p>
      </Section>

      <Section title="9. Changes to These Terms">
        <p>
          Terms may be updated as the platform grows. Continued use after an
          update constitutes acceptance of the revised terms.
        </p>
      </Section>
    </div>
  );
}
