const { DataTypes } = require("sequelize");
const crypto = require("crypto");
const bcrypt = require("bcryptjs");
const { sequelize } = require("../config/db");

// ── Referral code generation ────────────────────────────────────────────────
// 8 chars, uppercase, excludes visually-ambiguous characters (0/O, 1/I/L)
// so codes are easy to read aloud / retype from a screenshot.
const REFERRAL_CODE_ALPHABET = "ABCDEFGHJKMNPQRSTUVWXYZ23456789";
function generateReferralCode(len = 8) {
  let out = "";
  const bytes = crypto.randomBytes(len);
  for (let i = 0; i < len; i++) {
    out += REFERRAL_CODE_ALPHABET[bytes[i] % REFERRAL_CODE_ALPHABET.length];
  }
  return out;
}

const User = sequelize.define(
  "User",
  {
    id: {
      type: DataTypes.UUID,
      defaultValue: DataTypes.UUIDV4,
      primaryKey: true,
    },
    name: {
      type: DataTypes.STRING(80),
      allowNull: false,
      validate: {
        len: { args: [1, 80], msg: "Name cannot exceed 80 characters" },
        notEmpty: { msg: "Name is required" },
      },
    },
    email: {
      type: DataTypes.STRING,
      allowNull: false,
      unique: true,
      validate: {
        isEmail: { msg: "Please enter a valid email" },
        notEmpty: { msg: "Email is required" },
      },
      set(value) {
        this.setDataValue("email", value.toLowerCase().trim());
      },
    },
    password: {
      type: DataTypes.STRING,
      allowNull: true,
      validate: {
        passwordLength(value) {
          if (value && value.length < 8 && !value.startsWith("$2")) {
            throw new Error("Password must be at least 8 characters");
          }
        },
      },
    },
    // ── Google OAuth ──────────────────────────────────────────────────────────
    google_id: {
      type: DataTypes.STRING,
      allowNull: true,
      unique: true,
    },
    avatar: {
      type: DataTypes.STRING,
      allowNull: true,
    },
    // ─────────────────────────────────────────────────────────────────────────
    role: {
      type: DataTypes.ENUM("user", "admin"),
      defaultValue: "user",
    },
    streak: {
      type: DataTypes.INTEGER,
      defaultValue: 0,
    },
    longest_streak: {
      type: DataTypes.INTEGER,
      defaultValue: 0,
    },
    daily_target_hours: {
      type: DataTypes.INTEGER,
      defaultValue: 8,
      validate: { min: 1, max: 24 },
    },
    target_year: {
      type: DataTypes.INTEGER,
      defaultValue: () => new Date().getFullYear() + 1,
    },
    exam_date: {
      type: DataTypes.DATEONLY,
      defaultValue: () => {
        const d = new Date();
        d.setFullYear(d.getFullYear() + 1);
        d.setMonth(3);
        d.setDate(1);
        return d;
      },
    },
    quote: {
      type: DataTypes.TEXT,
      allowNull: true,
      defaultValue: null,
    },
    subscription_tier: {
      type: DataTypes.ENUM("free", "premium"),
      defaultValue: "free",
      allowNull: false,
    },
    subscription_source: {
      type: DataTypes.ENUM("none", "admin_grant", "razorpay", "trial", "referral"),
      defaultValue: "none",
      allowNull: false,
    },
    subscription_expires_at: {
      type: DataTypes.DATE,
      allowNull: true,
      defaultValue: null,
    },
    razorpay_customer_id: {
      type: DataTypes.STRING,
      allowNull: true,
      defaultValue: null,
    },
    // ── Referrals ──────────────────────────────────────────────────────────────
    referral_code: {
      type: DataTypes.STRING(12),
      allowNull: true, // generated by the hook below on create; nullable at the
      // DB level only so existing rows can be backfilled without a NOT NULL
      // migration failing on legacy data (see db.js v7 migration).
      unique: true,
    },
    referred_by: {
      // The id of the user whose referral_code was used at signup. Self-referencing
      // FK, set once at registration and never changed afterwards.
      type: DataTypes.UUID,
      allowNull: true,
      references: { model: "users", key: "id" },
    },
    referral_count: {
      // Denormalized count of successful referrals (i.e. how many people signed
      // up using this user's code) so the profile page can display it without
      // a COUNT() query on every /auth/me call.
      type: DataTypes.INTEGER,
      allowNull: false,
      defaultValue: 0,
    },
  },
  {
    tableName: "users",
    timestamps: true,
    underscored: true,
    hooks: {
      beforeSave: async (user) => {
        if (user.changed("password") && user.password) {
          const salt = await bcrypt.genSalt(12);
          user.password = await bcrypt.hash(user.password, salt);
        }
      },
        beforeValidate: async (user) => {
        if (user.referral_code || !user.isNewRecord) return;
        for (let attempt = 0; attempt < 5; attempt++) {
          const candidate = generateReferralCode(attempt < 3 ? 8 : 10);
          const clash = await User.findOne({ where: { referral_code: candidate } });
          if (!clash) {
            user.referral_code = candidate;
            return;
          }
        }
          user.referral_code = generateReferralCode(10) + Date.now().toString(36).toUpperCase();
      },
    },
  }
);

User.prototype.matchPassword = async function (enteredPassword) {
  if (!this.password) return false;
  return await bcrypt.compare(enteredPassword, this.password);
};

User.prototype.hasActivePremium = function () {
  if (this.subscription_tier !== "premium") return false;
  if (!this.subscription_expires_at) return true;
  return new Date(this.subscription_expires_at) > new Date();
};

module.exports = User;